config/routes.rb
ProjectMe::Application.routes.draw do

  devise_for :users
  resources :projects
  root :to => 'dashboards#index'
  resources :dashboards, :only => :index
  resources :pictures do
    get "download_file"
  end
  resources :comments
  resources :tasks
  resources :task_comments
  resources :photos do
    get "download_task_file"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :project_title, :project_created_by, :project_created_on, :project_details, :project_starts_on, :project_ends_on, :status, :invite_people, :user_id
  belongs_to :user
  STATUS = %w[Running Pending]
  has_many :pictures, as: :resource
  accepts_nested_attributes_for :pictures
  has_many :comments
  accepts_nested_attributes_for :comments
  has_many :tasks
  accepts_nested_attributes_for :tasks

  # Solar Search query
  # searchable do
  # 	text :project_title
  # end

  ####Simple Search#####
	def self.search(search)
	  if search
	    find(:all, :conditions => ['project_title LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authenticate_user!
	def index
		if params[:with] =="my_project"
		  @projects = current_user.projects.paginate(:page => params[:page], :per_page => 3).search(params[:search])
	  elsif params[:with] =="upcoming_project"
	  	@projects = Project.find_by_status("Pending")
	  	@projects = Project.paginate(:page => params[:page], :per_page => 3).search(params[:search])
    elsif params[:with] =="completed_project"
	  	@projects = Project.find_by_status("Completed")
		  @projects = Project.paginate(:page => params[:page], :per_page => 3).search(params[:search])
		elsif params[:with] == "project_tasks"
			@project = Project.find(params[:project_id])
			@projects = Project.paginate(:page => params[:page], :per_page => 3)
		else
			@projects = Project.paginate(:page => params[:page], :per_page => 3).search(params[:search])
    end
    @user = User.all
    @picture = Picture.all
    respond_to do |format|
    	format.html
    	format.js
    end
	end

	def new
		@project = Project.new
		# respond_to do |format|
  #     format.js
  #   end
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create
		@project = current_user.projects.create(params[:project])
		if @project
			redirect_to projects_path
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(:project)
			redirect_to project_path(@project)
		else
			render 'index'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		if @project.delete
			redirect_to projects_path
		else
			render 'index'
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_all_project.html.haml
- @projects.each_with_index do |project,i|
  .msgactive.msg{:id => "slideToggle_#{i}"}
    .profile_pic
      - if params[:with] =="my_project"
        = image_tag current_user.avatar.tiny.url
      -else
        = image_tag User.find_by_id(project.user_id).avatar.tiny.url
    .time_btn
      %a{href: "#"}
        = project.created_at.strftime("%H:%M")
    .content_text
      %h3
        = project.project_title
      %p
        = truncate("#{project.project_details}", :length => 70)
    .new_msgs
      = link_to projects_path(:with => "project_tasks", :project_id => project.id) do
        %h3
          = project.tasks.all.size
      %a{href: "#"} Tasks
      %p
        = project.project_starts_on.strftime("%m/%d/%y")
      %p
        = project.project_ends_on.strftime("%m/%d/%y")
    .drop_arrow
      %a{href: "#"} arrow
  .info_main_box
    .info
      = project.invite_people
      = image_tag "info.png"
      %textarea{cols: "50", rows: "4"}
        = project.project_details
    .info
      = project.status
      .attch_box
        .attach
          - project.pictures.each do |picture|
            -if picture.attachment.present?
              %li{:style => "list-style:none;padding:5px;"}
                %i.fa.fa-download
                = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                .delete_attachment
                  = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
        .attach
          = link_to "Attach New File", new_picture_path(:project_id => project.id), :class => "file_attach1", :remote => true
          %div.file_attach
          =# hidden_field_tag :project_id, :value => "#{project.id}"
    .info
      =image_tag "chat.png"
      .chat_box
        = link_to "Add Comment", new_comment_path(:project_id => project.id), :class => "add_comment1 btn btn-primary", :remote => true
        %div.add_comment
      .clearfix
      .line_bar
      .comment_box
        .user
          - project.comments.each do |comment|
            #comments_box
              .commented_user
                = image_tag current_user.avatar.tiny.url
                = link_to (current_user.first_name), root_path
                %span
                  = "#{time_ago_in_words(comment.created_at)} ago"
              - comment.pictures.each do |picture|
                %li{:style => "list-style:none;padding:5px;"}
                  -if picture.attachment.present?
                    %i.fa.fa-download
                    = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                    .delete_attachment
                      = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
                %p
                  = comment.add_comment
            .comment_border
      .clearfix

:javascript 

$(document).ready(function(){
  $('.info_main_box').hide();
  $(".msgactive").click(function(){
    var getID = this.id.split("_");
    $(this).prev('.info_main_box').hide();
    $(this).next('.info_main_box').slideToggle(1000);
  });
  $(window).load(function(){
    $("[data-toggle]").click(function() {
      var toggle_el = $(this).data("toggle");
      $(toggle_el).toggleClass("open-sidebar");
    });
  });
})

app/views/projects/_completed_project.html.haml
- @projects.each_with_index do |project,i|
  - if project.status == "Completed"
    .msgactive.msg{:id => "slideToggle_#{i}"}
      .profile_pic
        - if params[:with] =="my_project"
          = image_tag current_user.avatar.tiny.url
        -else
          = image_tag User.find_by_id(project.user_id).avatar.tiny.url
      .time_btn
        %a{href: "#"}
          = project.created_at.strftime("%H:%M")
      .content_text
        %h3
          = project.project_title
        %p
          = truncate("#{project.project_details}", :length => 70)
      .new_msgs
        = link_to projects_path(:with => "project_tasks", :project_id => project.id) do
          %h3
            = project.tasks.all.size
        %a Tasks
        %p
          = project.project_starts_on.strftime("%m/%d/%y")
        %p
          = project.project_ends_on.strftime("%m/%d/%y")
      .drop_arrow
        %a{href: "#"} arrow
    .info_main_box
      .info
        = project.invite_people
        %textarea{cols: "50", rows: "4"}
          = project.project_details
      .info
        = project.status
        .attch_box
          .attach
            - project.pictures.each do |picture|
              - if picture.attachment.present?
                %li{:style => "list-style:none;padding:5px;"}
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
          .attach
            = link_to "Attach New File", new_picture_path(:project_id => project.id), :class => "file_attach1", :remote => true
            %div.file_attach
            =# hidden_field_tag :project_id, :value => "#{project.id}"
      .info
        =image_tag "chat.png"
        .chat_box
          = link_to "Add Comment", new_comment_path(:project_id => project.id), :class => "add_comment1 btn btn-primary", :remote => true
          %div.add_comment
          %a{href: "#"}
            = image_tag "attachment.png"
        .clearfix  
        .line_bar
        .comment_box
          - project.comments.each do |comment|
            %li{:style => "list-style:none"}
              =# User.find_by_id(comment.user_id).first_name
              = comment.add_comment
            - comment.pictures.each do |picture|
              %li{:style => "list-style:none;padding:5px;"}
                -if picture.attachment.present?
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
        .clearfix

:javascript 

$(document).ready(function(){
  $('.info_main_box').hide();
  $(".msgactive").click(function(){
    var getID = this.id.split("_");
    $(this).prev('.info_main_box').hide();
    $(this).next('.info_main_box').slideToggle(1000);
  });
  $(window).load(function(){
    $("[data-toggle]").click(function() {
      var toggle_el = $(this).data("toggle");
      $(toggle_el).toggleClass("open-sidebar");
    });
  });
})

app/views/projects/_form.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog"}
  = form_for @project do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4#myModalLabel.modal-title Project Form
        .modal-body
          .control-group
            = f.label(:project_title, :class => "control-label")
            .controls
              = f.text_field :project_title
          .control-group
            = f.label(:created_by, :class => "control-label")
            .controls
              = f.text_field :created_by
          .control-group
            = f.label(:created_at, :class => "control-label")
            .controls
              = f.text_field :created_at, :id => "project_created_date"
          .control-group
            = f.label(:project_details, :class => "control-label")
            .controls
              = f.text_field :project_details
          .control-group
            = f.label(:starts_at, :class => "control-label")
            .controls
              = f.text_field :starts_at, :id => "project_start"
          .control-group
            = f.label(:ends_at, :class => "control-label")
            .controls
              = f.text_field :ends_at, :id => "project_end"
          .control-group
            = f.label(:status, :class => "control-label")
            .controls
              = f.select :status, Project::STATUS.collect{|v, k| [v, k]}, :prompt => "please select option"
          .control-group
            = f.label(:invite_people, :class => "control-label")
            .controls
              = f.select :invite_people, User.all.collect{|a| a.first_name}, :prompt => "please select option"
          .control-group
            = f.submit "Save", :class => "btn btn-primary"

:javascript
  $(document).ready(function(){
    $('#project_created_at').datepicker({
      calendarWeeks: true,
      autoclose: true,
      todayHighlight: true
    });
    $('#project_starts_at').datepicker({
      calendarWeeks: true,
      autoclose: true,
      todayHighlight: true
    });
    $('#project_ends_at').datepicker({
      calendarWeeks: true,
      autoclose: true,
      todayHighlight: true
    });
  })

app/views/projects/_my_project.html.haml
- @projects.each_with_index do |project,i|
  - if project.project_created_by == current_user.first_name
    .msgactive.msg{:id => "slideToggle_#{i}"}
      .profile_pic
        - if params[:with] =="my_project"
          = image_tag current_user.avatar.tiny.url
        - else
          = image_tag User.find_by_id(project.user_id).avatar.tiny.url
      .time_btn
        %a{href: "#"}
          = project.created_at.strftime("%H:%M")
      .content_text
        %h3
          = project.project_title
        %p
          = truncate("#{project.project_details}", :length => 70)
      .new_msgs
        = link_to projects_path(:with => "project_tasks", :project_id => project.id) do
          %h3
            = project.tasks.all.size
        %a Tasks
        %p
          = project.project_starts_on.strftime("%m/%d/%y")
        %p
          = project.project_ends_on.strftime("%m/%d/%y")
      .drop_arrow
        %a{href: "#"} arrow
    .info_main_box
      .info
        = project.invite_people
        %textarea{cols: "50", rows: "4"}
          = project.project_details
      .info
        = project.status
        .attch_box
          .attach
            - project.pictures.each do |picture|
              - if picture.attachment.present?
                %li{:style => "list-style:none;padding:5px;"}
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
          .attach
            = link_to "Attach New File", new_picture_path(:project_id => project.id), :class => "file_attach1", :remote => true
            %div.file_attach
            =# hidden_field_tag :project_id, :value => "#{project.id}"
      .info
        =image_tag "chat.png"
        .chat_box
          = link_to "Add Comment", new_comment_path(:project_id => project.id), :class => "add_comment1 btn btn-primary", :remote => true
          %div.add_comment
          %a{href: "#"}
            = image_tag "attachment.png"
        .clearfix  
        .line_bar
        .comment_box
          - project.comments.each do |comment|
            %li{:style => "list-style:none"}
              =# User.find_by_id(comment.user_id).first_name
              = comment.add_comment
            - comment.pictures.each do |picture|
              %li{:style => "list-style:none;padding:5px;"}
                - if picture.attachment.present?
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
        .clearfix

:javascript 

$(document).ready(function(){
  $('.info_main_box').hide();
  $(".msgactive").click(function(){
    var getID = this.id.split("_");
    $(this).prev('.info_main_box').hide();
    $(this).next('.info_main_box').slideToggle(1000);
  });
  $(window).load(function(){
    $("[data-toggle]").click(function() {
      var toggle_el = $(this).data("toggle");
      $(toggle_el).toggleClass("open-sidebar");
    });
  });
})

app/views/projects/_project.html.haml
.tab_bg  
.tabs
  %ul
    %li
      %a{href: projects_path(:with=>"all_project"), :id => "all_project"} All Projects
    %li
      %a{href: projects_path(:with=>"my_project"), :id => "my_project"} My Projects
    %li
      %a{href: projects_path(:with => "upcoming_project"), :id => "upcoming_project"} Upcoming Projects
    %li
      %a{href: projects_path(:with => "completed_project"), :id => "completed_project"} Completed Projects
.clearfix

-if params[:with] == "upcoming_project"
  = render :partial => "upcoming_project"

- elsif params[:with] == "completed_project"
  = render :partial => "completed_project"

- elsif params[:with] == "my_project"
  = render :partial => "my_project"

- elsif params[:with] == "project_tasks"
  = render :partial => "project_tasks"

- else
  = render :partial => "all_project"

app/views/projects/_project_tasks.html.haml
- if @project.tasks.present?
  - @project.tasks.each_with_index do |task, i|
    .msg_active.msg{:id => "slideToggle_#{i}"}
      .profile_pic
        - if params[:with] =="task_section" || params[:with] =="all_task"
          = image_tag User.find_by_id(task.user_id).avatar.tiny.url
        -else
          = image_tag current_user.avatar.tiny.url
      .time_btn
        %a{href: "#"}
          = task.created_at.strftime("%H:%M")
      .content_text
        %h3
          = task.title
        %p
          = truncate("#{task.task_details}", :length => 70)
      .new_msgs
        = #link_to (project.tasks.all.size), tasks_path
        %p
          = #task.starts_on
        %p
          =# task.ends_on
      .drop_arrow
        %a{href: "#"} arrow
    .info_main_box
      .info
        =# project.invite_people
        = image_tag "info.png"
        %textarea{cols: "50", rows: "4"}
          = task.task_details
      .info
        = #task.status
        .attch_box
          .attach
            - task.photos.each do |photo|
              -if photo.document.present?
                %li{:style => "list-style:none;padding:5px;"}
                  %i.fa.fa-download
                  = link_to "#{photo.document.file.filename}", photo_download_task_file_path(photo)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), photo, :method => :delete, :confirm => "Are you sure"
          .attach
            = link_to "Attach New File", new_photo_path(:task_id => task.id), :class => "file_attach2", :remote => true
            %div.task_file_attach
      .info
        = image_tag "chat.png"
        .chat_box
          = link_to "Add Comment", new_task_comment_path(:task_id => task.id), :class => "add_comment1 btn btn-primary", :remote => true
          %div.add_task_comment
        .clearfix  
        .line_bar
        .comment_box
          .user
            - task.task_comments.each do |comment|
              #comments_box
                .commented_user
                  = #image_tag current_user.avatar.tiny.url
                  %a
                    = comment.task_comment_created_by
                  %span
                    = "#{time_ago_in_words(comment.created_at)} ago"
                %li{:style => "list-style:none"}
                  - comment.photos.each do |photo|
                    - if photo.document.present?
                      %li{:style => "list-style:none; padding:5px;"}
                        %i.fa.fa-download
                        = link_to "#{photo.document.file.filename}", photo_download_task_file_path(photo)
                        .delete_attachment
                          = link_to image_tag("delete.jpeg"), photo, :method => :delete, :confirm => "Are you sure", :id => "task_comment_doc"
                  %p
                    = comment.add_task_comment
              .comment_border
        .clearfix
- else
  #projects_tasks
    There is no Task related to this project.

:javascript
  $(document).ready(function(){
    $('.info_main_box').hide();
    $(".msg_active").click(function(){
      var getID = this.id.split("_");
      $(this).prev('.info_main_box').hide();
      $(this).next('.info_main_box').slideToggle(1000);
    });
    $(window).load(function(){
      $("[data-toggle]").click(function() {
        var toggle_el = $(this).data("toggle");
        $(toggle_el).toggleClass("open-sidebar");
      });
    });
    // Adding actibe class on click task links //
    $("#all_task").click(function(){
      $(this).addClass("active")
    })
    $("#my_task").click(function(){
      $(this).addClass("active")
    })
    $("#upcoming_task").click(function(){
      $(this).addClass("active")
    })
    $("#completed_task").click(function(){
      $(this).addClass("active")
    })

    $(".file_attach").on('click',function(){
      $(".file_attach").val($("#project_id").html());
    })
  })

app/views/projects/_right_content.html.haml
.log_time
  %a{href: "#"} + Start or Log Time
  .tracking_time
    %h5 1 Person Tracking Time
    .user_tracking
      .profile_pic
        / %img{alt: "", src: "images/profile_png.png"}/
      .user_name
        %h3 Richard Peter
        %p Create Live Projects User Interface
      .time_btn
        %a{href: "#"} 5:30
    .your_time
      %h5 Your Time
      .tracker
        %span Today
        %span.line  
        %span.time 03:23
      .tracker
        %span Yesterday
        %span.line1  
        %span.time 07:21
      .tracker
        %span This Week
        %span.line1  
        %span.time 07:21
      .tracker
        %span Last Week
        %span.line1  
        %span.time 07:21
      .tracker
        %span This Month
        %span.line1  
        %span.time 07:21
      .tracker
        %span Last Month
        %span.line1  
        %span.time 07:21
    .recent_activity
      %h5 Recent Activity
      .activity_recent
        %a{href: "#"} Thiyagu
        post new comment on Task
        %span Create Live Projects User Interface
      .activity_recent
        %a{href: "#"} Sumanth
        added a new project
        %span Mockups.me
      .activity_recent
        %a{href: "#"} Sumanth
        added a new resource
        %span Ajay
        to Project
        %span Live List
      .activity_recent
        %a{href: "#"} Thiyagu
        attached
        %span Sample Mockups.jpg
        to Project
        %span Mockups.me
      .activity_recent
        %a{href: "#"} Thiyagu
        changed his status to
        %span In progress
        for Task
        %span Create Live Projects User Interface
      %a.more{href: "#"} View More

app/views/projects/_upcoming_project.html.haml
- @projects.each_with_index do |project,i|
  - if project.status == "Pending"
    .msgactive.msg{:id => "slideToggle_#{i}"}
      .profile_pic
        - if params[:with] =="my_project"
          = image_tag current_user.avatar.tiny.url
        -else
          = image_tag User.find_by_id(project.user_id).avatar.tiny.url
      .time_btn
        %a{href: "#"}
          = project.created_at.strftime("%H:%M")
      .content_text
        %h3
          = project.project_title
        %p
          = truncate("#{project.project_details}", :length => 70)
      .new_msgs
        = link_to projects_path(:with => "project_tasks", :project_id => project.id) do
          %h3
            = project.tasks.all.size
        %a Tasks
        %p
          = project.project_starts_on.strftime("%m/%d/%y")
        %p
          = project.project_ends_on.strftime("%m/%d/%y")
      .drop_arrow
        %a{href: "#"} arrow
    .info_main_box
      .info
        = project.invite_people
        %textarea{cols: "50", rows: "4"}
          = project.project_details
      .info
        = project.status
        .attch_box
          .attach
            - project.pictures.each do |picture|
              -if picture.attachment.present?
                %li{:style => "list-style:none;padding:5px;"}
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
          .attach
            = link_to "Attach New File", new_picture_path(:project_id => project.id), :class => "file_attach1", :remote => true
            %div.file_attach
            =# hidden_field_tag :project_id, :value => "#{project.id}"
      .info
        =image_tag "chat.png"
        .chat_box
          = link_to "Add Comment", new_comment_path(:project_id => project.id), :class => "add_comment1 btn btn-primary", :remote => true
          %div.add_comment
          %a{href: "#"}
            = image_tag "attachment.png"
        .clearfix  
        .line_bar
        .comment_box
          - project.comments.each do |comment|
            %li{:style => "list-style:none"}
              = comment.add_comment
            - comment.pictures.each do |picture|
              %li{:style => "list-style:none;padding:5px;"}
                -if picture.attachment.present?
                  %i.fa.fa-download
                  = link_to "#{picture.attachment.file.filename}", picture_download_file_path(picture)
                  .delete_attachment
                    = link_to image_tag("delete.jpeg"), picture, :method => :delete, :confirm => "Are you sure"
        .clearfix

:javascript 

$(document).ready(function(){
  $('.info_main_box').hide();
  $(".msgactive").click(function(){
    var getID = this.id.split("_");
    $(this).prev('.info_main_box').hide();
    $(this).next('.info_main_box').slideToggle(1000);
  });
  $(window).load(function(){
    $("[data-toggle]").click(function() {
      var toggle_el = $(this).data("toggle");
      $(toggle_el).toggleClass("open-sidebar");
    });
  });
})

app/views/projects/edit.html.haml
= #render :partial => "form"

app/views/projects/index.html.haml
.content_area
  .content_header
    %a{href: "#"}
      Show Project Details
      = image_tag "arrow.png"
    #project_pagination
      = will_paginate(@projects, :renderer => WillPaginate::ActionView::LinkRenderer)
    .search_project
      = form_tag projects_path, :method => :get, :id => "projects_search", :remote => true do
        %p
          = text_field_tag :search, params[:search], :class => "search_text"
          = submit_tag "GO", :name => nil, :class => "btn btn-primary project_search_button"
  #project
    = render :partial => "project"

.content_right
  = render :partial => "right_content"

.footer

:javascript

$(document).ready(function () {
  $('.pagination .previous_page').text('«');
  $('.pagination .next_page').text('»');

  $('.pagination').each(function () {
    var $bar = $(this);
    $bar.find('a, .current, span').wrapAll('<ul>');
    $bar.find('a, .current, span').wrap('<li>');

    $bar.find('em').each(function () {
      $(this).parent().addClass('disabled');
      $(this).replaceWith('<a href="#">' + $(this).text() + '</a>');
    });
  });
});

app/views/projects/index.js.haml
$("#project").html("#{escape_javascript(render :partial => "project")}");

app/views/projects/new.html.haml
=# render :partial => "form"

app/views/projects/new.js.haml
$("#create_new_project").html("#{escape_javascript(render :partial => "form")}");

app/views/projects/show.html.haml
%div
  %b
    Project Title
  = @project.project_title

%div
  %b
    Project Created By
  = @project.project_created_by

%div
  %b
    Project Created At
  = @project.project_created_on

%div
  %b
    Project Details
  = @project.project_details

%div
  %b
    Project Starts At
  = @project.project_starts_on

%div
  %b
    Project Ends At
  = @project.project_ends_on

%div
  %b
    Project Status
  = @project.status

%div
  %b
    Invite People
  = @project.invite_people

= link_to "All Projects", projects_path